sudo: required
language: node_js
node_js: stable
cache:
  directories:
  - "node_modules"

script: bash ./deploy.sh

# branches:
#   only:
#     -master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  local-dir: .vuepress/dist
  on:
    branch: master
